// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjcTlmEZcV2oFAcHOvmii996-hxydK7u0',
    appId: '1:1054469295335:web:287e14313e88b44bcce642',
    messagingSenderId: '1054469295335',
    projectId: 'souk-f53b5',
    authDomain: 'souk-f53b5.firebaseapp.com',
    storageBucket: 'souk-f53b5.appspot.com',
    measurementId: 'G-3MYHK6YSHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY8nHypsWhzSo_I1Uq_XRLhRtAMw0JAhE',
    appId: '1:1054469295335:android:608b926442f365dbcce642',
    messagingSenderId: '1054469295335',
    projectId: 'souk-f53b5',
    storageBucket: 'souk-f53b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUqI3PIUaSVQ0nvvKgzDwWw2TTf26GCz4',
    appId: '1:1054469295335:ios:131182dfb322d83acce642',
    messagingSenderId: '1054469295335',
    projectId: 'souk-f53b5',
    storageBucket: 'souk-f53b5.appspot.com',
    androidClientId: '1054469295335-qv9rfulp05g2vbb45k98ou3f4cdq66sa.apps.googleusercontent.com',
    iosClientId: '1054469295335-apllgigd598qn8a0d9r93tar1npnv6cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.soukapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUqI3PIUaSVQ0nvvKgzDwWw2TTf26GCz4',
    appId: '1:1054469295335:ios:131182dfb322d83acce642',
    messagingSenderId: '1054469295335',
    projectId: 'souk-f53b5',
    storageBucket: 'souk-f53b5.appspot.com',
    androidClientId: '1054469295335-qv9rfulp05g2vbb45k98ou3f4cdq66sa.apps.googleusercontent.com',
    iosClientId: '1054469295335-apllgigd598qn8a0d9r93tar1npnv6cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.soukapp',
  );
}
